### ISSUE TITLE
[ASK] allow deep-linking of HTML outputs

### ISSUE THREAD

**Issue by revodavid** [microsoft/forecasting#190]
### Description
Would it be possible to add a [`gh-pages` branch](https://help.github.com/en/github/working-with-github-pages/about-github-pages#publishing-sources-for-github-pages-sites), so we can link directly to the HTML outputs, [like this one](https://revodavid.github.io/forecasting/examples/grocery_sales/R/01_dataprep.nb.html) for example?

This is particularly useful for the R Markdown outputs (.Rmd), which Github doesn't render.

### Other Comments

**Comment by vapaunic** [comment]
Thanks for the suggestion @revodavid . We'll work on this, and update the issue once it's done.

**Comment by vapaunic** [comment]
Hi @revodavid, we've added a github page to the repo, for rendering html outputs. See example here:
https://microsoft.github.io/forecasting/examples/grocery_sales/R/01_dataprep.nb.html

Thanks again for your suggestion. I'll close this issue now. Let us know if you have any other comments.

**Comment by revodavid** [comment]
Thanks! I updated my blog post to use the corrected links: https://blog.revolutionanalytics.com/2020/04/forecasting-best-practices-from-microsoft.html
