### ISSUE TITLE
[ASK] 

### ISSUE THREAD

**Issue by chengzchengzhan** [microsoft/forecasting#197]
### Description
For the demo notebook azure_automl_single_round.ipynb
https://github.com/microsoft/forecasting/blob/master/examples/grocery_sales/python/00_quick_start/azure_automl_single_round.ipynb
I noticed that we Combine AutoML Model with a Custom Model in the end, wondering whether we try the enable_voting_ensemble or enable_stacking_ensemble in automl and see whether it might be better. 

### Other Comments

**Comment by chenhuims** [comment]
Thanks @chengzchengzhan. In AutoML, ensemble models are enabled by default according to https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-auto-train#ensemble. More specifically, `enable_voting_ensemble` and `enable_stack_ensemble` are set to be True by default. These settings only control the combination of models trained by AutoML but not a custom model. As far as I know, after the best model is found by AutoML, we will still need to manually combine it with a custom model.
