### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HandsomeLuoyang** [microsoft/forecasting#198]
### I get an error when running.
![image](https://user-images.githubusercontent.com/52132083/81647262-48a81380-945f-11ea-93df-f49df331dbbd.png)
### how can i solve it?

**Comment by vapaunic** [comment]
Hello, thank you for reporting this.

Can you please double check the version of the scrapbook module you have installed? If you followed the setup instructions, a conda environment `forecasting_env` is created from the `tools/environment.yaml` file. In this file we're installing a specific version of scrapbook module, `nteract-scrapbook==0.3.1`, so this is the version that should be installed. We also provide instructions on how to register this environment as a Jupyter kernel, so the installed packages are accessible from the notebooks. Could you confirm that you followed these steps?

If you open a python session in the environment `forecasting_env` created from the yaml file, and try running the following few commands, this is what the output should look like:

![image](https://user-images.githubusercontent.com/15053814/81721139-41b7db80-9434-11ea-9a5e-3b1ebd53cbbd.png)

**Comment by HandsomeLuoyang** [comment]
Sorry, I installed the library in the wrong way. Now I've installed it the right way and it's ready to use. I sincerely thank you for your help.
And the right way to install the library is `pip install nteract-scrapbook==0.3.1`。

**Comment by vapaunic** [comment]
Hi, great, glad you solved it. Thanks for reaching out.
