### ISSUE TITLE
[BUG] Most recent pmdarima causes version conflicts, setup problems

### ISSUE THREAD

**Issue by hongooi73** [microsoft/forecasting#211]
### Description

The latest pmdarima is 1.6.1 as of 2020-06-27, which requires numpy >= 1.17.3 and scikit-learn >= 0.22. The forecasting_env environment pins these to 1.16.2 and 0.20.3 respectively. This also impacts new setup, as the tools/environment_setup.sh script aborts when the error is encountered, leaving the setup half-done.

### How do we replicate the bug?

1. Have a fresh Ubuntu VM or local machine
2. Clone the repo
3. Execute the setup commands
    - Notice the following lines in the output:

```
ERROR: pmdarima 1.6.1 has requirement numpy>=1.17.3, but you'll have numpy 1.16.2 which is incompatible.
ERROR: pmdarima 1.6.1 has requirement scikit-learn>=0.22, but you'll have scikit-learn 0.20.3 which is incompatible.
```

The rest of the [setup script](https://github.com/microsoft/forecasting/blob/master/tools/environment_setup.sh) after after line 14 is not executed, so eg fclib and ray are not installed.

**Comment by hongooi73** [comment]
Related: in this line, "ray>=0.8.2" should be quoted

https://github.com/microsoft/forecasting/blob/bc47741cb10f8fce6a073a1542b7aeec4fdc1e52/tools/environment_setup.sh#L20

**Comment by vapaunic** [comment]
@hongooi73 , is this bug resolved with the above merge? If so, please close it.
