### ISSUE TITLE
Refactoring fclib

### ISSUE THREAD

**Issue by hongooi73** [microsoft/forecasting#215]
The current fclib modules are a legacy from the tsperf iteration of this repo. They have a number of issues:

- Contain functions which are idiosyncratic to the energy forecasting use case, eg computing lags for specific seasonality definitions
- Other functions carry implicit assumptions about the nature of the data, eg exactly 2 key/grain variables
- Lack of unit tests

These make fclib less suitable as a general-purpose toolkit for enabling forecasting. This issue is to track progress in refactoring the library into something that better fits this description.

**Comment by hongooi73** [comment]
Should remove integer output arg for modelling utility funcs, this just adds needless complexity.

**Comment by vapaunic** [comment]
@hongooi73 , is this issue addressed with your latest work on code refactoring and unit tests?

**Comment by hongooi73** [comment]
Not yet, there are more changes I want to make as we discussed before.

**Comment by hongooi73** [comment]
- Refactor the one-hot-encoding functions to always return a fixed number of columns

**Comment by vapaunic** [comment]
Hi @hongooi73 , with the latest changes in one-hot-encoding functions, is this issue resolved?

**Comment by hongooi73** [comment]
Yeah let's close this for now.
