### ISSUE TITLE
[FEATURE] Add Naïve forecasting benchmark

### ISSUE THREAD

**Issue by rasyidstat** [microsoft/forecasting#221]
### Description
A simple Naïve forecasting benchmark in R and Python 

### Expected behavior with the suggested feature

Help people to get a quick and simple benchmark in forecasting

**Comment by vapaunic** [comment]
Hi, thanks for the suggestion. Just to clarify, you're suggesting we include a Naive model to the R and Python examples? We do already have a Naive model under R examples in this example: https://github.com/microsoft/forecasting/blob/master/examples/grocery_sales/R/02_basic_models.Rmd 

Is this what you had in mind?

**Comment by rasyidstat** [comment]
Sorry, I did not see it. 
I think that we need to add Naïve model to the documentation then.
