### ISSUE TITLE
[ASK] 

### ISSUE THREAD

**Issue by MGCodesandStats** [microsoft/forecasting#223]
### Description
I am attempting to run the _lightgbm_multi_round.ipynb_ notebook. I am using Python 3.6.9.

However, when importing the relevant libraries, I get the error message: **ModuleNotFoundError: No module named 'fclib.common'**.

I have installed fclib and common-utils separately, but when trying to install fclib.common through _pip3 install fclib.common_, I get the error message: **(ERROR: Could not find a version that satisfies the requirement fclib.common)**.

Any advice or assistance would be greatly appreciated.

### Other Comments

**Comment by winnieshen96** [comment]
Met the same problem as well. Any solutions yet?

**Comment by winnieshen96** [comment]
I just found out that on pip fclib is another library. Can someone please package this library to pip? I myself want to use this library on Databricks, and it's not convenient to use this library there.

**Comment by adenysenko** [comment]
+1
