### ISSUE TITLE
[FEATURE] lightgbm R example

### ISSUE THREAD

**Issue by hongooi73** [microsoft/forecasting#229]
Hi @vapaunic @chenhuims,

I note that lightgbm is [now on CRAN](https://cran.r-project.org/web/packages/lightgbm/index.html). Would you be interested in an R example using this? Probably a copy of the current Python OJ example, or maybe I can find a new use case.

**Comment by chenhuims** [comment]
@hongooi73 An R example using lightgbm from CRAN sounds a great idea. Please feel free to create a PR to add such example using either OJ data or any other license friendly dataset. Thanks!
