### ISSUE TITLE
[FEATURE] Use tidyverts datasets

### ISSUE THREAD

**Issue by hongooi73** [microsoft/forecasting#57]
https://tsibbledata.tidyverts.org/

**Comment by Hong-Revo** [comment]
Current OJ dataset is unusual in the context of time series datasets: no trend or seasonality, but plenty of independent variables. Should have an example that exhibits "standard" behaviour for comparative purposes: trend, seasonality, etc. This will allow demonstration of TS methods in a proper light.

@mitchelloharawild

**Comment by hongooi73** [comment]
Closed in #200
